#!/usr/bin/env python3
# -------------------------------------------------------------------------
# Copyright (c) 2019 - 2026 by the OpFlow developers
# All rights reserved.
#
# This file is part of OpFlow.
#
# OpFlow is free software and is distributed under the MPL v2.0 license.
# -------------------------------------------------------------------------

import argparse
import json
import os
from pathlib import Path
import re
import subprocess


def run_conda_command(conda_exe: str, args):
    cmd = [conda_exe] + args
    proc = subprocess.run(
        cmd, check=False, capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"Conda command failed: {' '.join(cmd)}\n{proc.stderr.strip()}"
        )
    return proc.stdout


def detect_conda_executable():
    conda_exe = os.environ.get("CONDA_EXE")
    if conda_exe and Path(conda_exe).exists():
        return conda_exe
    return "conda"


def parse_conda_env_prefixes(conda_exe: str, target: str):
    raw = run_conda_command(conda_exe, ["env", "list", "--json"])
    data = json.loads(raw)
    envs = [Path(p).resolve() for p in data.get("envs", [])]
    if Path(target).name == "base":
        root_prefix = data.get("root_prefix")
        if root_prefix:
            return Path(root_prefix).resolve()
        raise RuntimeError("Could not resolve base environment path from conda json output.")
    for env_path in envs:
        if env_path.name == target:
            return env_path
    # allow passing absolute or relative path directly in env list output
    for env_path in envs:
        if str(env_path) == str(Path(target).resolve()):
            return env_path
    raise RuntimeError(
        f"Conda environment '{target}' not found. "
        f"Use `conda env list` to confirm available environments."
    )


def is_conda_prefix(path: Path):
    return path.is_dir() and (path / "conda-meta").is_dir() and (path / "bin").is_dir()


def resolve_prefix(target: str, conda_exe: str):
    candidate = Path(target).expanduser().resolve()
    if target and is_conda_prefix(candidate):
        return candidate
    if os.path.isabs(target) or target.startswith("."):
        raise RuntimeError(
            f"{target} looks like a path but does not look like a conda environment "
            f"(missing bin/ and conda-meta)."
        )
    return parse_conda_env_prefixes(conda_exe, target)


def normalize_preset_name(name):
    normalized = re.sub(r"[^a-zA-Z0-9_.-]", "-", name.strip())
    return normalized if normalized else "opflow-conda"


def write_settings(vscode_dir: Path):
    settings = {
        "cmake.configureOnOpen": False,
        "cmake.useCMakePresets": "always",
        "cmake.generator": "Ninja",
        "cmake.preferredGenerators": [
            "Ninja"
        ],
    }
    (vscode_dir / "settings.json").write_text(
        json.dumps(settings, indent=2) + "\n", encoding="utf-8"
    )


def write_cmake_presets(vscode_dir: Path, preset_name: str, prefix_dir: Path):
    configure_name = normalize_preset_name(preset_name)
    presets = {
        "version": 6,
        "configurePresets": [
            {
                "name": configure_name,
                "displayName": f"Conda ({configure_name})",
                "description": "Configure using an explicit conda environment.",
                "generator": "Ninja",
                "binaryDir": f"${{sourceDir}}/build/{configure_name}",
                "toolchainFile": "${sourceDir}/.vscode/conda-toolchain.cmake",
                "cacheVariables": {
                    "OPFLOW_BUILD_EXAMPLES": "ON",
                    "OPFLOW_BUILD_TESTS": "ON",
                    "OPFLOW_BUILD_BENCHMARKS": "ON",
                    "OPFLOW_BUILD_DOCS": "OFF",
                    "CMAKE_C_COMPILER": str(prefix_dir / "bin/gcc"),
                    "CMAKE_CXX_COMPILER": str(prefix_dir / "bin/g++"),
                },
            }
        ],
        "buildPresets": [
            {
                "name": f"{configure_name}-release",
                "displayName": f"{configure_name} (Release)",
                "configurePreset": configure_name,
            }
        ],
    }
    presets["configurePresets"][0]["cacheVariables"]["CMAKE_VERBOSE_MAKEFILE"] = "OFF"
    presets["configurePresets"][0]["cacheVariables"]["CMAKE_PREFIX_PATH"] = str(prefix_dir)
    (vscode_dir / "CMakePresets.json").write_text(
        json.dumps(presets, indent=2) + "\n", encoding="utf-8"
    )


def write_toolchain(vscode_dir: Path, prefix_dir: Path):
    gcc = prefix_dir / "bin/gcc"
    gxx = prefix_dir / "bin/g++"
    if not gcc.exists():
        raise RuntimeError(f"Cannot find gcc in {prefix_dir}/bin")
    if not gxx.exists():
        raise RuntimeError(f"Cannot find g++ in {prefix_dir}/bin")
    content = f"""# Generated by scripts/generate_vscode_toolchain.py
set(_conda_prefix "{prefix_dir}")

if (NOT EXISTS "${{_conda_prefix}}/bin/gcc" OR NOT EXISTS "${{_conda_prefix}}/bin/g++")
  message(FATAL_ERROR "Compiler not found in conda env: ${{_conda_prefix}}")
endif()

set(CMAKE_C_COMPILER "${{_conda_prefix}}/bin/gcc" CACHE FILEPATH "C compiler from conda env" FORCE)
set(CMAKE_CXX_COMPILER "${{_conda_prefix}}/bin/g++" CACHE FILEPATH "C++ compiler from conda env" FORCE)
set(CMAKE_PREFIX_PATH "${{_conda_prefix}}" CACHE PATH "Conda env prefix for dependencies" FORCE)

set(ENV{{CC}} "${{_conda_prefix}}/bin/gcc")
set(ENV{{CXX}} "${{_conda_prefix}}/bin/g++")
"""
    (vscode_dir / "conda-toolchain.cmake").write_text(content, encoding="utf-8")


def write_cpp_properties(vscode_dir: Path, prefix_dir: Path, build_dir: str):
    build_path = "${workspaceFolder}/build/" + build_dir
    properties = {
        "version": 4,
        "configurations": [
            {
                "name": "opflow-conda",
                "compilerPath": str(prefix_dir / "bin/g++"),
                "compilerArgs": ["-std=c++20"],
                "cStandard": "gnu11",
                "cppStandard": "gnu++20",
                "intelliSenseMode": "linux-gcc-x64",
                "configurationProvider": "ms-vscode.cmake-tools",
                "includePath": [
                    "${workspaceFolder}/**",
                    f"{prefix_dir}/include",
                    "${workspaceFolder}/src",
                ],
                "browse": {
                    "path": [
                        "${workspaceFolder}/**",
                        f"{prefix_dir}/include",
                        "${workspaceFolder}/src",
                    ],
                    "limitSymbolsToIncludedHeaders": True,
                },
                "compileCommands": build_path + "/compile_commands.json",
            }
        ],
    }
    (vscode_dir / "c_cpp_properties.json").write_text(
        json.dumps(properties, indent=2) + "\n", encoding="utf-8"
    )


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Generate VSCode toolchain files for a target conda environment."
        )
    )
    parser.add_argument(
        "environment",
        nargs="?",
        default=None,
        help=(
            "Conda environment name or absolute path. "
            "If omitted, defaults to $CONDA_PREFIX."
        ),
    )
    parser.add_argument(
        "--workspace",
        default=".",
        help="Workspace root (default: current directory)",
    )
    parser.add_argument(
        "--preset-name",
        default=None,
        help="Preset base name (default: opflow-conda)",
    )
    args = parser.parse_args()

    conda_exe = detect_conda_executable()
    if args.environment is None:
        env_from_default = os.environ.get("CONDA_PREFIX")
        if not env_from_default:
            raise RuntimeError(
                "No environment argument provided and CONDA_PREFIX is not set. "
                "Set CONDA_PREFIX or pass an env name/path explicitly."
            )
        prefix_dir = Path(env_from_default).expanduser().resolve()
        if not is_conda_prefix(prefix_dir):
            raise RuntimeError(
                f"CONDA_PREFIX='{env_from_default}' is not a valid conda environment "
                f"(missing bin/ and conda-meta)."
            )
    else:
        prefix_dir = resolve_prefix(args.environment, conda_exe)
    vscode_dir = Path(args.workspace).resolve() / ".vscode"
    vscode_dir.mkdir(parents=True, exist_ok=True)

    preset_name = args.preset_name or prefix_dir.name
    normalized_preset = normalize_preset_name(preset_name)

    write_settings(vscode_dir)
    write_cmake_presets(vscode_dir, normalized_preset, prefix_dir)
    write_toolchain(vscode_dir, prefix_dir)
    write_cpp_properties(vscode_dir, prefix_dir, normalized_preset)

    print(f"Generated VSCode toolchain files under {vscode_dir}")
    print(f"Conda prefix: {prefix_dir}")
    print(f"Preset name: {normalized_preset}")


if __name__ == "__main__":
    main()
